name: check-fail-workflow-weekly

on:
  workflow_dispatch:
  schedule:
  - cron: '1 1 * * 4'

jobs:
  fribidi-amd-zen4plus:
    runs-on: windows-latest
    steps:
    - uses: actions/cache@v4
      id: cache
      with:
        path: D:\msys64
        key: mcf_20250722_15.1.1_x64-ucrt
    - name: Prepare
      run: git config --global core.autocrlf false
    - uses: actions/checkout@v4
    - name: Build
      env:
        C_INCLUDE_PATH: /opt/include
        CPLUS_INCLUDE_PATH: /opt/include
        LIBRARY_PATH: /opt/lib
        MSYSTEM: UCRT64
      run: |
        D:\msys64\usr\bin\bash -lc 'cp /d/a/mpv-win64/mpv-win64/amd-zen4+.conf /etc/makepkg.conf; cd /d/a/mpv-win64/mpv-win64/fribidi-dev; PATH=/usr/bin:/opt/bin:/ucrt64/bin PKG_CONFIG_PATH=/opt/lib/pkgconfig makepkg'
    - name: Delete
      uses: mknejp/delete-release-assets@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: dev-amd-zen4+
        assets: fribidi*
        fail-if-no-assets: false
        fail-if-no-release: false
    - name: Upload
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: fribidi-dev/*.zst
        tag: dev-amd-zen4+
        overwrite: true
        file_glob: true

  luajit-amd-zen4plus:
    runs-on: windows-latest
    steps:
    - uses: actions/cache@v4
      id: cache
      with:
        path: D:\msys64
        key: mcf_20250722_15.1.1_x64-ucrt
    - name: Prepare
      run: git config --global core.autocrlf false
    - uses: actions/checkout@v4
    - name: Build
      env:
        C_INCLUDE_PATH: /opt/include
        CPLUS_INCLUDE_PATH: /opt/include
        LIBRARY_PATH: /opt/lib
        MSYSTEM: UCRT64
      run: |
        D:\msys64\usr\bin\bash -lc 'cp /d/a/mpv-win64/mpv-win64/amd-zen4+.conf /etc/makepkg.conf; cd /d/a/mpv-win64/mpv-win64/luajit; PATH=/usr/bin:/opt/bin:/ucrt64/bin PKG_CONFIG_PATH=/opt/lib/pkgconfig makepkg'
    - name: Delete
      uses: mknejp/delete-release-assets@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: latest-amd-zen4+
        assets: luajit*
        fail-if-no-assets: false
        fail-if-no-release: false
    - name: Delete Dev
      uses: mknejp/delete-release-assets@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: dev-amd-zen4+
        assets: luajit*
        fail-if-no-assets: false
        fail-if-no-release: false
    - name: Upload
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: luajit/*pkg*.xz
        tag: latest-amd-zen4+
        overwrite: true
        file_glob: true
    - name: Upload Dev
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: luajit/*.zst
        tag: dev-amd-zen4+
        overwrite: true
        file_glob: true
